version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: silain-postgres-prebuilt
    environment:
      POSTGRES_DB: silain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./Backend/db/silain.sql:/docker-entrypoint-initdb.d/silain.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d silain"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.prebuilt
    container_name: silain-app-prebuilt
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: silain
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
